// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLtxuyRh7pEP0mNDJ014vLU4UZbdJJU6E',
    appId: '1:527638029360:web:072b06b7d21b54d40839f5',
    messagingSenderId: '527638029360',
    projectId: 'todolist-3d96f',
    authDomain: 'todolist-3d96f.firebaseapp.com',
    storageBucket: 'todolist-3d96f.appspot.com',
    measurementId: 'G-X06L61TX1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_Mn4Zzt_c-Ce3lDEIc-q2156heDJsAg',
    appId: '1:527638029360:android:383378fac06d63180839f5',
    messagingSenderId: '527638029360',
    projectId: 'todolist-3d96f',
    storageBucket: 'todolist-3d96f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEKce-wULGjqvw8qtFzaRKQ5dXpDXw0w',
    appId: '1:527638029360:ios:99323a731bc39a700839f5',
    messagingSenderId: '527638029360',
    projectId: 'todolist-3d96f',
    storageBucket: 'todolist-3d96f.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEKce-wULGjqvw8qtFzaRKQ5dXpDXw0w',
    appId: '1:527638029360:ios:a18c0df1532a9f910839f5',
    messagingSenderId: '527638029360',
    projectId: 'todolist-3d96f',
    storageBucket: 'todolist-3d96f.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
