// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFbZrJKuFL84y8llIRGDjTd89F7qZTGyU',
    appId: '1:175870162528:web:3d069412d7bcd6cfee3505',
    messagingSenderId: '175870162528',
    projectId: 'milan-csit-6th-sem',
    authDomain: 'milan-csit-6th-sem.firebaseapp.com',
    storageBucket: 'milan-csit-6th-sem.appspot.com',
    measurementId: 'G-ZY3EKQ0FS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZknIk_gwgvbkl9BGNciHVpr_GJnWKtg',
    appId: '1:175870162528:android:7cb356eaf9d77743ee3505',
    messagingSenderId: '175870162528',
    projectId: 'milan-csit-6th-sem',
    storageBucket: 'milan-csit-6th-sem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEuk8u4ge3Eb0zfu7ydX1nnvZOl81rE4',
    appId: '1:175870162528:ios:c449d83c2e5d5771ee3505',
    messagingSenderId: '175870162528',
    projectId: 'milan-csit-6th-sem',
    storageBucket: 'milan-csit-6th-sem.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEuk8u4ge3Eb0zfu7ydX1nnvZOl81rE4',
    appId: '1:175870162528:ios:b13a3341c3a59e8bee3505',
    messagingSenderId: '175870162528',
    projectId: 'milan-csit-6th-sem',
    storageBucket: 'milan-csit-6th-sem.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
